package org.hartford.greensure.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hartford.greensure.enums.Zone;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Stores the computed carbon footprint score for a declaration.
 * Generated by CarbonScoreService immediately after the field agent
 * submits a CONFIRMED or MODIFIED verification outcome.
 *
 * Contains a full breakdown of all CO₂ components (vehicle, electricity,
 * cooking, solar offset, lifestyle bonus) and the complete discount
 * calculation (zone + improvement + duration, capped at 35%).
 *
 * discountBreakdown is stored as a JSON string for easy transmission
 * to the frontend without a join query.
 */
@Entity
@Table(name = "carbon_scores")
@Getter @Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CarbonScore {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "score_id")
    private Long scoreId;

    @Column(name = "score_year", nullable = false)
    private Integer scoreYear;

    // ── CO₂ COMPONENT BREAKDOWN ────────────────────────────────

    @Column(name = "vehicle_co2")
    private Double vehicleCo2;

    @Column(name = "electricity_co2")
    private Double electricityCo2;

    @Column(name = "cooking_co2")
    private Double cookingCo2;

    /** CO₂ offset from verified solar installation. Stored as positive value. */
    @Column(name = "solar_offset")
    private Double solarOffset;

    /** Total bonus reduction from lifestyle module (public transport + recycling). */
    @Column(name = "lifestyle_bonus")
    private Double lifestyleBonus;

    // ── TOTALS ─────────────────────────────────────────────────

    @Column(name = "total_co2", nullable = false)
    private Double totalCo2;

    /** total CO₂ divided by number of household members. */
    @Column(name = "per_capita_co2", nullable = false)
    private Double perCapitaCo2;

    // ── ZONE & DISCOUNT ────────────────────────────────────────

    @Enumerated(EnumType.STRING)
    @Column(name = "zone", nullable = false)
    private Zone zone;

    /** Total discount percentage (capped at 35%). */
    @Column(name = "discount_percent")
    private Double discountPercent;

    @Column(name = "zone_discount_percent")
    private Double zoneDiscountPercent;

    @Column(name = "improvement_bonus_percent")
    private Double improvementBonusPercent;

    @Column(name = "duration_discount_percent")
    private Double durationDiscountPercent;

    /**
     * JSON representation of the discount breakdown for frontend display.
     * Example: {"zone":30.0,"improvement":8.0,"duration":5.0,"total":35.0,"cap":35}
     */
    @Column(name = "discount_breakdown", columnDefinition = "TEXT")
    private String discountBreakdown;

    /** Plain-language AI summary (Gemini); optional. */
    @Column(name = "ai_explanation", columnDefinition = "TEXT")
    private String aiExplanation;

    @Column(name = "generated_at", updatable = false)
    private LocalDateTime generatedAt;

    // ── RELATIONS ──────────────────────────────────────────────

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "declaration_id", nullable = false, unique = true)
    private CarbonDeclaration declaration;

    @OneToMany(mappedBy = "score", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<Recommendation> recommendations = new ArrayList<>();

    // ── LIFECYCLE ──────────────────────────────────────────────

    @PrePersist
    protected void onCreate() {
        this.generatedAt = LocalDateTime.now();
    }
}
